module.exports = [
    ["RFID", "Radio Frequency Identification"],
    ["NFC", "Near Field Communication"],
    ["ESN", "Enterprise Social Networking"],
    ["REEF", "Retainable Evaluator Execution Framework"],
    ["SDE", "Software Defined Everything"],
    ["NBIC", "Nanotechnology, Biotechnology, Information Technology, Cognitive Science"],
    ["AWS", "Amazon Web Services"],
    ["S3", "Simple Storage System"],
    ["GCP", "Google Cloud Platform"],
    ["GCLB", "Google Cloud Load Balancer"],
    ["AMI", "Amazon Machine Image"],
    ["ARN", "Amazon Resource Name"],
    ["EC2", "Elastic Compute Cloud"],
    ["ECS", "EC2 Container Service"],
    ["EFS", "Elastic File System"],
    ["EMR", "Elastic Map Reduce"],
    ["SWS", "Simple Workflow Service"],
    ["SNS", "Simple Notification Service"],
    ["GCS", "Google Cloud Storage"],
    ["VPC", "Virtual Private Cloud"],
    ["AZ", "Availability Zone"],
    ["ASG", "Auto Scaling Group"],
    ["EBS", "Elastic Block Store"],
    ["ELB", "Elastic Load Balancer"],
    ["EIP", "Elastic IP"],
    ["ENI", "Elastic Network Interface"],
    ["HPC", "High Performance Compute"],
    ["HVM", "Hardware Virtual Machine"],
    ["S3IA", "S3 Infrequent Access"],
    ["IG", "Internet Gateway"],
    ["KMS", "Key Management Service"],
    ["RRS", "Reduced Redundancy Storage"],
    ["SQS", "Simple Queue Service"],
    ["TPM", "Trusted Platform Module"],
    ["VPG", "Virtual Private Gateway"],
    ["VPS", "Virtual Private Server"],
    ["HPCSA", "HP Cloud Service Automation"],
    ["SEO", "Search Engine Optimization"],
    ["SCM", "Search Content Marketing"],
    ["SEM", "Search Engine Marketing"],
    ["WP", "WordPress"],
    ["PPC", "Pay Per Click"],
    ["CPC", "Cost Per Click"],
    ["SERP", "Search Engine Results Page"],
    ["CTS", "Click Through Rate"],
    ["CR", "Conversion Rate"],
    ["CPM", "Cost Per Thousand Impressions"],
    ["SVG", "Scalable Vector Graphics"],
    ["DMCA", "Digital Millennium Copyright Act"],
    ["CMS", "Content Management System"],
    ["CRO", "Conversion Rate Optimization"],
    ["CTA", "Call to Action"],
    ["CTR", "Click Through Rate"],
    ["PR", "PageRank"],
    ["DA", "Domain Authority"],
    ["ROI", "Return on Investment"],
    ["UIUX", "User Interface User Experience"],
    ["SEA", "Search Engine Advertising"],
    ["SMO", "Social Media Optimization"],
    ["SMM", "Social Media Marketing"],
    ["SERM", "Search Engine Reputation Management"],
    ["AMA", "Ask Me Anything"],
    ["B2B", "Business to Business"],
    ["B2C", "Business to Consumer"],
    ["CRM", "Customer Relationship Management"],
    ["CX", "Customer Experience"],
    ["FOMO", "Fear of Missing Out"],
    ["GA", "Google Analytics"],
    ["IO", "Insertion Order"],
    ["SM", "Social Media"],
    ["SMP", "Social Media Platform"],
    ["UA", "Universal Analytics"],
    ["CPL", "Cost Per Lead"],
    ["NPS", "Net Promoter Score"],
    ["QDD", "Query Deserves Diversity"],
    ["QDF", "Query Deserves Freshness"],
    ["SC", "Supplementary Content"],
    ["ZMOT", "Zero Moment of Truth"],
    ["HITS", "Hyperlink Induced Topic Search"],
    ["LSI", "Latent Semantic Indexing"],
    ["PBN", "Private Blog Network"],
    ["AI", "Artificial Intelligence"],
    ["IMS", "Intelligent Maintenance Systems"],
    ["ML", "Machine Learning"],
    ["NI", "Natural Intelligence"],
    ["MI", "Machine Intelligence"],
    ["NLP", "Natural Language Processing"],
    ["CNN", "Convolutional Neural Network"],
    ["RNN", "Recurrent Neural Network"],
    ["LSTM", "Long Short term Memory"],
    ["CTC", "Connectionist Temporal Classification"],
    ["CV", "Computer Vision"],
    ["HMD", "Head Mounted Displays"],
    ["RL", "Reinforcement Learning"],
    ["NLNN", "Non Learning Neural Networks"],
    ["SR", "Speech Recognition"],
    ["M2M", "Machine to Machine"],
    ["DSBS", "Dual Sensor Brake Support"],
    ["LNN", "Learning Neural Networks"],
    ["NLU", "Natural Language Understanding"],
    ["RPA", "Robotic Process Automation"],
    ["ANN", "Artificial Neural Network"],
    ["SQL", "Structured Query Language"],
    ["DQL", "Data Query Language"],
    ["DDL", "Data Definition Language"],
    ["DML", "Data Manipulation Language"],
    ["RDSMS", "Relational Data Stream Management System"],
    ["OLAP", "Online Analytical Processing"],
    ["OLTP", "Online Transaction Processing"],
    ["DRDA", "Distributed Relational Database Architecture"],
    ["4DQL", "4D Query Language"],
    ["DMS", "Database Migration Service"],
    ["FIFO", "First In First Out"],
    ["PHP", "Hypertext Preprocessor"],
    ["HTML", "Hypertext Markup Language"],
    ["JS", "JavaScript"],
    ["CSS", "Cascading Style Sheets"],
    ["API", "Application Programming Interface"],
    ["XML", "Extensible Markup Language"],
    ["SOAP", "Simple Object Access Protocol"],
    ["XHTML", "Extensible Hypertext Markup Language"],
    ["JSON", "JavaScript Object Notation"],
    ["EOF", "End Of File"],
    ["SDK", "Software Development Kit"],
    ["ASCII", "American Standard Code for Information Interchange"],
    ["I0", "Input and Output"],
    ["WYSIWYG", "What You See Is What You Get"],
    ["VCS", "Version Control Systems"],
    ["IDE", "Integrated Development Environment"],
    ["EOL", "End Of Life"],
    ["XSD", "XML Schema Definition"],
    ["VBS", "Visual Basic Script"],
    ["RAD", "Rapid Application Development"],
    ["JCE", "Java Cryptography Extension"],
    ["JDK", "Java Development Kit"],
    ["IPSec", "Internet Protocol Security"],
    ["SSE", "Server Side Encryption"],
    ["SSL", "Secure Socket Layer"],
    ["TLS", "Transport Layer Security"],
    ["DOS", "Denial of Services"],
    ["DDoS", "Distributed Denial Of Services"],
    ["XSS", "Cross site Scripting"],
    ["CSP", "Content Security Policy"],
    ["CSRF", "Cross Site Request Forgery"],
    ["SQLi", "SQL Injection"],
    ["CBSP", "Cloud based Security Providers"],
    ["ACL", "Access Control List"],
    ["AES", "Advanced Encryption System"],
    ["CORS", "Cross Origin Resource Sharing"],
    ["IAM", "Identity and Access Management"],
    ["MFA", "Multi Factor Authentication"],
    ["WAF", "Web Application Firewall"],
    ["OWASP", "Open Web Application Security Project"],
    ["MITM", "Man in the Middle Attack"],
    ["SAML", "Security Assertion Markup Language"],
    ["STS", "Security Token Service"],
    ["FUD", "Fully Undetectable"],
    ["RAT", "Remote Administration Tool"],
    ["SE", "Social Engineering"],
    ["SKid", "Script Kiddie"],
    ["DNSSEC", "Domain Name System Security Extensions"],
    ["DKIM", "Domain Keys Identified Mail"],
    ["SPF", "Sender Policy Framework"],
    ["CVSS", "Common Vulnerability Scoring System"],
    ["SAST", "Static Application Security Testing"],
    ["DAST", "Dynamic Application Security Testing"],
    ["WAP", "Web Application Protection"],
    ["RFI", "Remote File Inclusion"],
    ["LFI", "Local File Inclusion"],
    ["DT", "Directory Traversal"],
    ["PT", "Path Traversal"],
    ["SCD", "Source Code Disclosure"],
    ["OSCI", "OS Command Injection"],
    ["CWE", "Common Weakness Enumeration"],
    ["DSA", "Digital Signature Algorithm"],
    ["DES", "Data Encryption Standard"],
    ["OSS", "Open Source Software"],
    ["FOSS", "Free and open source software"],
    ["OS", "Operating System"],
    ["HA", "High Availability"],
    ["BYOD", "Bring Your Own Device"],
    ["VM", "Virtual Machine"],
    ["KVM", "Kernel based Virtual Machine"],
    ["ESX", "Elastic Sky X"],
    ["DRS", "Distributed Resource Scheduler"],
    ["VSM", "Virtual Supervisor Module"],
    ["QEMU", "Quick Emulator"],
    ["SSD", "Solid state Drive"],
    ["IOPS", "Input output Operations Per Second"],
    ["ADFS", "Active Directory Federation Service"],
    ["CLI", "Command Line Interface"],
    ["CICD", "Continous Integration, Continous Deployment"],
    ["SSH", "Secure Shell"],
    ["MSTSC", "Microsoft Terminal Service Client"],
    ["MPP", "Massive Parallel Processing"],
    ["NFS", "Network File System"],
    ["RAID", "Redundant Array of Independent Disk"],
    ["RAM", "Random access Memory"],
    ["SLA", "Service Level Agreement"],
    ["OLA", "Operational level Agreement"],
    ["SSO", "Single Sign On"],
    ["VTL", "Virtual Tape Library"],
    ["VDI", "Virtual Desktop Infrastructure"],
    ["BIOS", "Basic Input Output System"],
    ["DVD", "Digital Versatile Disc"],
    ["PSU", "Power Supply Unit"],
    ["ROM", "Read Only Memory"],
    ["UPS", "Uninterruptible Power Supply"],
    ["DC", "Data Center"],
    ["GUI", "Graphical User Interface"],
    ["TPU", "Tensor Processing Unit"],
    ["RISC", "Reduced Instruction Set Computer"],
    ["AU", "Activation Unit"],
    ["ALU", "Arithmetic Logic Units"],
    ["AVX", "Advanced Vector Extensions"],
    ["P2V", "Physical to Virtual"],
    ["VXLAN", "Virtual Extensible Local Area Network"],
    ["HAC", "High availability Clusters"],
    ["RUM", "Real user Measurement"],
    ["ERP", "Enterprise Resource Planning"],
    ["BPO", "Business Process Outsourcing"],
    ["BI", "Business Intelligence"],
    ["IT", "Information Technology"],
    ["DW", "Data Warehouse"],
    ["WINS", "Windows Internet Name Service"],
    ["WMI", "Windows Management Instrumentation"],
    ["VG", "Volume Group"],
    ["TTY", "Teletype"],
    ["SFTP", "SSH File Transfer Protocol"],
    ["SAN", "Storage Area Network"],
    ["DNS", "Domain Name System"],
    ["HTTP", "Hyper Text Transport Protocol"],
    ["HTTPS", "Hyper Text Transport Protocol Secure"],
    ["CDN", "Content Delivery Network"],
    ["LAN", "Local Area Network"],
    ["WAN", "Wide Area Network"],
    ["DHCP", "Dynamic Host Configuration Protocol"],
    ["TCP", "Transmission Control Protocol"],
    ["IP", "Internet Protocol"],
    ["WWW", "World Wide Web"],
    ["D2D", "Device to Device"],
    ["VPN", "Virtual Private Network"],
    ["BGP", "Border Gateway Protocol"],
    ["VLAN", "Virtual Local Area Network"],
    ["DOM", "Document Object Model"],
    ["UDP", "User Datagram Protocol"],
    ["CIDR", "Classless Inter Domain Routing"],
    ["VIP", "Virtual IP"],
    ["ICMP", "Internet Control Message Protocol"],
    ["LB", "Load Balancer"],
    ["SMTP", "Simple Mail Transfer Protocol"],
    ["FTP", "File Transfer Protocol"],
    ["RDP", "Remote Desktop Protocol"],
    ["MPLS", "Multi Protocol Label Switching"],
    ["NS", "Name Server"],
    ["NAT", "Network Address Translation"],
    ["SOA", "Start of Authority"],
    ["TTL", "Time To Live"],
    ["TPS", "Transaction Per Second"],
    ["NDA", "Nondisclosure Agreement"],
    ["AP", "Access Point"],
    ["MAC", "Media Access Control"],
    ["NIC", "Network Interface Card"],
    ["ISP", "Internet Service Provider"],
    ["URL", "Uniform Resource Locator"],
    ["PDF", "Portable Document Format"],
    ["TLD", "Top level domain"],
    ["RSS", "Really Simple Syndication"],
    ["IFTTT", "If This Then That"],
    ["IE", "Internet Explorer"],
    ["AFAIK", "As Far as I Know"],
    ["DM", "Direct Message"],
    ["FB", "Facebook"],
    ["PM", "Private Message"],
    ["MIME", "Multipurpose Internet Mail Extensions"],
    ["POP", "Post Office Protocol"],
    ["IMAP", "Internet Message Access Protocol"],
    ["CNAME", "Canonical Name"],
    ["MX", "Mail Exchange"],
    ["PPTP", "Point to Point Tunneling Protocol"],
    ["LLT", "Low Latency Transport"],
    ["ASN", "Autonomous System Number"],
    ["SCM", "Supply Chain Management"],
    ["WPAN", "Wireless Personal Area Network"],
    ["WLAN", "Wireless Local Area Network"],
    ["URI", "Uniform Resource Identifier"],
    ["TTF", "TrueType Font"],
    ["NACK", "Negative ACKnowledgement"],
    ["HAR", "HTTP Archive"],
    ["2moro", "Tomorrow"],
    ["2nte", "Tonight"],
    ["AEAP", "As Early as Possible"],
    ["ALAP", "As Late as Possible"],
    ["ASAP", "As Soon as Possible"],
    ["ASL", "Age Sex Location"],
    ["B3", "Blah, Blah, Blah"],
    ["B4YKI", "Before You Know it"],
    ["BFF", "Best Friends, Forever"],
    ["BRB", "Be right Back"],
    ["BRT", "Be right There"],
    ["BTAM", "Be that as it May"],
    ["C P", "Sleepy"],
    ["CTN", "Cannot talk now"],
    ["CUS", "See You Soon"],
    ["CWOT", "Complete Waste of Time"],
    ["CYT", "See You Tomorrow"],
    ["E123", "Easy as 1, 2, 3"],
    ["EOD", "End of Day"],
    ["F2F", "Face to Face"],
    ["FC", "Fingers Crossed"],
    ["FOAF", "Friend of a Friend"],
    ["GR8", "Great"],
    ["HAK", "Hugs and Kisses"],
    ["IDC", "I Don't Care"],
    ["IDK", "I Don't Know"],
    ["ILUILY", "I Love You"],
    ["IMU", "I Miss You"],
    ["IRL", "In Real Life"],
    ["JK", "Just Kidding"],
    ["JC", "Just Checking"],
    ["JTLYK", "Just to Let You Know"],
    ["KFY", "Kiss for You"],
    ["KMN", "Kill Me Now"],
    ["KPC", "Keeping Parents Clueless"],
    ["L8R", "Later"],
    ["MTFBWY", "May the Force be with You"],
    ["MYOB", "Mind Your Own Business"],
    ["N A Y L", "In a While"],
    ["NAZ", "Name, Address, ZIP"],
    ["NC", "No Comment"],
    ["NIMBY", "Not in my Backyard"],
    ["NM", "Never Mind Nothing Much"],
    ["NP", "No Problem"],
    ["NSFW", "Not Safe for Work"],
    ["NTIM", "Not that it Matters"],
    ["NVM", "Never Mind"],
    ["OATUS", "On a totally Unrelated Subject"],
    ["OIC", "Oh, I See"],
    ["OMW", "On My Way"],
    ["OTL", "Out to Lunch"],
    ["OTP", "On the Phone"],
    ["P911", "Parent Alert"],
    ["PAL", "Parents are Listening"],
    ["PAW", "Parents are Watching"],
    ["PIR", "Parent in Room"],
    ["POS", "Parent over Shoulder"],
    ["PROPS", "Proper Respect Proper Recognition"],
    ["QT", "Cutie"],
    ["RN", "Right Now"],
    ["RU", "Are You"],
    ["SEP", "Someone else's Problem"],
    ["SITD", "Still in the Dark"],
    ["SLAP", "Sounds like a Plan"],
    ["SMIM", "Send Me an Instant Message"],
    ["SO", "Significant Other"],
    ["TMI", "Too Much Information"],
    ["UR", "Your You are"],
    ["W8", "Wait"],
    ["WB", "Welcome Back"],
    ["WYCM", "Will You Call Me"],
    ["WYWH", "Wish You Were Here"],
    ["XOXOXOX", "Hugs, Kisses, ,,,"],
    ["2F4U", "Too Fast For You"],
    ["4YEOFYEO", "For Your Eyes Only"],
    ["AAMOF", "As a Matter of Fact"],
    ["ACK", "Acknowledgment"],
    ["AFAIK", "As far as I know"],
    ["AFAIR", "As far as I remember recall"],
    ["AFK", "Away from Keyboard"],
    ["AKA", "Also known as"],
    ["B2KBTK", "Back to Keyboard"],
    ["BTT", "Back to Topic"],
    ["BTW", "By the Way"],
    ["BC", "Because"],
    ["CU", "See you"],
    ["CYS", "Check your Settings"],
    ["DIY", "Do it Yourself"],
    ["EOBD", "End of Business Day"],
    ["EOD", "End of Discussion"],
    ["EOM", "End of Message"],
    ["EOT", "End of Thread ,, Text ,, Transmission"],
    ["FAQ", "Frequently asked Questions"],
    ["FACK", "Full Acknowledge"],
    ["FKA", "Formerly known as"],
    ["FWIW", "For what it's Worth"],
    ["FYI", "For your Information"],
    ["FTW", "Fuck the World For the Win"],
    ["HF", "Have fun"],
    ["HTH", "Hope this Helps"],
    ["IDK", "I don't know"],
    ["IIRC", "If I Recall Remember Correctly"],
    ["IMHO", "In my Humble Opinion"],
    ["IMO", "In my Opinion"],
    ["IMNSHO", "In my not so Humble Honest Opinion"],
    ["IOW", "In other Words"],
    ["ITT", "In this Thread"],
    ["LOL", "Laughing out loud"],
    ["DGMW", "Don't get me wrong"],
    ["MMW", "Mark my Words"],
    ["NA", "Not Available Applicable"],
    ["NNTR", "No need to Reply"],
    ["NOYB", "None of your Business"],
    ["NRN", "No Reply Necessary"],
    ["OMG", "Oh my God"],
    ["OP", "Original Poster, Original Post"],
    ["OT", "Off Topic"],
    ["OTOH", "On the other Hand"],
    ["PEBKAC", "Problem exists between Keyboard and Chair"],
    ["POV", "Point of View"],
    ["ROTFL", "Rolling on the Floor Laughing"],
    ["RSVP", "Repondez s'il vous plait"],
    ["RSVP", "Please reply"],
    ["RTFM", "Read the fine Manual"],
    ["SCNR", "Sorry could not Resist"],
    ["SFLR", "Sorry for late Reply"],
    ["SPOC", "Single Point of Contact"],
    ["TBA", "To be Announced"],
    ["TBC", "To be Continued To be Confirmed"],
    ["TIA", "Thanks in Advance"],
    ["TGIF", "Thanks God, its Friday"],
    ["THXTNX", "Thanks"],
    ["TQ", "Thank You"],
    ["TYVM", "Thank You Very Much"],
    ["TYT", "Take your Time"],
    ["TTYL", "Talk to you Later"],
    ["WFM", "Works for Me"],
    ["WRT", "With Regard to"],
    ["WTH", "What the Hell What the Heck"],
    ["WTF", "What the Fuck"],
    ["YMMD", "You made my Day"],
    ["YMMV", "Your Mileage may vary"],
    ["YAM", "Yet Another Meeting"],
    ["ICYMI", "In Case you missed it"],
    ["AFK", "Away From Keyboard"],
    ["BBIAB", "Be Back In A Bit"],
    ["BBL", "Be Back Later"],
    ["BBS", "Be Back Soon"],
    ["BEG", "Big Evil Grin"],
    ["BRB", "Be Right Back"],
    ["BTW", "By The Way"],
    ["EG", "Evil Grin"],
    ["FISH", "First In, Still Here"],
    ["IDK", "I Don't Know"],
    ["IMO", "In My Opinion"],
    ["IRL", "In Real Life"],
    ["KISS", "Keep It Simple, Stupid"],
    ["LOL", "Laughing Out Loud"],
    ["NYOB", "None of Your Business"],
    ["OMG", "Oh My God"],
    ["PANS", "Pretty Awesome New Stuff"],
    ["PHAT", "Pretty, Hot, And Tempting"],
    ["POS", "Parents Over Shoulder"],
    ["TTYL", "Talk To You Later"],
    ["ASAP", "As Soon As Possible"],
    ["AWOL", "Absent Without Leave"],
    ["CIA", "Central Intelligence Agency"],
    ["CPS", "Child Protective Services"],
    ["CSI", "Crime Scene Investigation"],
    ["DAFB", "Dover Air Force Base"],
    ["DMV", "Division of Motor Vehicles"],
    ["DNC", "Democratic National Committee"],
    ["FBI", "Federal Bureau of Investigation"],
    ["FUBAR", "Fucked Up Beyond All Recognition"],
    ["MIA", "Missing In Action"],
    ["OSHA", "Occupational Safety and Health Administration"],
    ["NAFTA", "North American Free Trade Agreement"],
    ["NASA", "National Aeronautics and Space Administration"],
    ["POTUS", "President of the United States"],
    ["POW", "Prisoner Of War"],
    ["RNC", "Republican National Committee"],
    ["SCOTUS", "Supreme Court of the United States"],
    ["SWAT", "Special Weapons And Tactics"],
    ["ABS", "Anti lock Braking System"],
    ["ADD", "Attention Deficit Disorder"],
    ["ADHD", "Attention Deficit Hyperactivity Disorder"],
    ["AIDS", "Acquired Immune Deficiency Syndrome"],
    ["AMA", "Against Medical Advice"],
    ["CDC", "Centers for Disease Control and Prevention"],
    ["DARE", "Drug Abuse Resistance Education"],
    ["DOA", "Dead On Arrival"],
    ["DOB", "Date Of Birth"],
    ["DIY", "Do It Yourself"],
    ["FAQ", "Frequently Asked Questions"],
    ["GIF", "Graphics Interchange Format"],
    ["HIV", "Human Immunodeficiency Virus"],
    ["MD", "Medical Doctor"],
    ["OTC", "Over The Counter"],
    ["PPV", "Pay Per View"],
    ["RADAR", "Radio Detection And Ranging"],
    ["SONAR", "Sound Navigation And Ranging"],
    ["SUV", "Sports Utility Vehicle"],
    ["UFO", "Unidentified Flying Object"],
    ["AKA", "Also Known As"],
    ["CAPTCHA", "turing test, Completely Automated Public Turing Test to tell Computers and Humans Apart"],
    ["CST", "Central Standard Time"],
    ["DAEMON", "Disk And Execution Monitor"],
    ["DBA", "Doing Business As"],
    ["DND", "Do Not Disturb"],
    ["EDS", "Electronic Data Systems"],
    ["EOD", "End of Day"],
    ["EST", "Eastern Standard Time"],
    ["ETA", "Estimated Time of Arrival"],
    ["HR", "Human Resources"],
    ["MBA", "Masters of Business Administration"],
    ["MST", "Mountain Standard Time"],
    ["NASDAQ", "National Association of Securities Dealers Automated Quotation"],
    ["OT", "Overtime"],
    ["POS", "Point Of Service"],
    ["PST", "Pacific Standard Time"],
    ["SWOT", "Strengths, Weaknesses, Opportunities, Threats"],
    ["SMARTGoals", "Specific, Measurable, Attainable, Realistic, Time bound Goals"],
    ["TEDTalk", "Tell me, Explain to me, Describe to me"],
    ["AA", "Alcoholics Anonymous"],
    ["AAAS", "American Association for the Advancement of Science"],
    ["AARP", "American Association of Retired Persons"],
    ["ADA", "American Dental Association"],
    ["AFL", "American Football League"],
    ["AMA", "American Medical Association"],
    ["APA", "American Psychological Association"],
    ["ESPN", "Entertainment and Sports Programming Network"],
    ["FLAG", "Foreign Language Association of Georgia"],
    ["MADD", "Mothers Against Drunk Driving"],
    ["MLA", "Modern Language Association"],
    ["NBA", "National Basketball Association"],
    ["NFL", "National Football League"],
    ["NHL", "National Hockey League"],
    ["PAWS", "Progressive Animal Welfare Society"],
    ["PGA", "Professional Golfer's Association"],
    ["SPCA", "Society for the Prevention of Cruelty to Animals"],
    ["SWF", "Single White Female"],
    ["SWM", "Single White Male"],
    ["WWE", "World Wrestling Entertainment"],
    ["BKPR", "Bookkeeper"],
    ["CAO", "Chief Accounting Officer"],
    ["CEO", "Chief Executive Officer"],
    ["CFO", "Chief Financial Officer"],
    ["CIO", "Chief Information Officer"],
    ["CMO", "Chief Marketing Officer"],
    ["COO", "Chief Operating Officer"],
    ["CPA", "Certified Public Accountant"],
    ["CTO", "Chief Technology Officer"],
    ["PRO", "Public Relations Officer"],
    ["HRM", "Human Resource Manager"],
    ["CDO", "Chief Data Officer"],
    ["RMP", "Risk Management Professional"],
    ["AAMS", "Accredited Asset Management Specialist"],
    ["AASA", "Assistant Area Sales Advisor"],
    ["AAVP", "Associate Administrator for Veterans Programs"],
    ["AB", "Administrative Board"],
    ["ABCP", "Associate Business Continuity Planner"],
    ["ABM", "Area Business Manager"],
    ["ABR", "Accredited Buyer’s Representative"],
    ["ABW", "Activity Based Workplace"],
    ["AC", "Academic Counselor"],
    ["ACC", "Association Corporate Counsel"],
    ["AD", "Assistant Deputy"],
    ["AD", "Assistant Director"],
    ["ADC", "Assistant District Commissioner"],
    ["ADAF", "Associate Director of Administration and Finance"],
    ["ADI", "Advanced Driving Instructor"],
    ["ADOF", "Associate Director of Finance"],
    ["ADRP", "Assistant Director for Research and Planning"],
    ["AM", "Administration Manager"],
    ["ABA", "Accredited Business Accountant"],
    ["AM", "Accounts Manager"],
    ["AA", "Accounting Assistant"],
    ["STRATCOM", "Strategic Communications"],
    ["ADR", "Associate Dean for Research"],
    ["ADU", "Academic Development Unit"],
    ["PA", "Personal Assistant"],
    ["ACCG", "Accounting"],
    ["ACCT", "Account"],
    ["ACR", "Accrual"],
    ["ACV", "Actual Cash Value"],
    ["AGI", "Adjusted Gross Income"],
    ["AGR", "Adjusted Gross Revenue"],
    ["AIR", "Assumed Interest Rate"],
    ["AP", "Accounts Payable"],
    ["APR", "Annual Percentage Rate"],
    ["ARM", "Adjustable Rate Mortgage"],
    ["BGT", "Budget"],
    ["BS", "Balance Sheet"],
    ["CAGR", "Compound Annual Growth Rate"],
    ["CAP", "Capital"],
    ["CAPEX", "Capital Expenditures"],
    ["CD", "Certificate of Deposit"],
    ["CF", "Cash flow"],
    ["COB", "Close of Business"],
    ["COGS", "Cost of Goods Sold"],
    ["CPA", "Certified Public Accountant"],
    ["CR", "Credit"],
    ["DR", "Debit"],
    ["EA", "Enrolled Agent"],
    ["EFT", "Electronic Funds Transfer"],
    ["EPS", "Earnings Per Share"],
    ["ETF", "Exchange Traded Funds"],
    ["FA", "Fixed Assets"],
    ["CA", "Current Assets"],
    ["FDIC", "Federal Deposit Insurance Corporation"],
    ["FIFO", "First In, First Out"],
    ["FOREX", "Foreign Exchange"],
    ["FRB", "Federal Reserve Board"],
    ["GAAP", "Generally Accepted Accounting Principles"],
    ["GL", "General Ledger"],
    ["GNP", "Gross National Product"],
    ["GP", "Gross Profit"],
    ["IRA", "Individual Retirement Account"],
    ["LC", "Letter of Credit"],
    ["LIFO", "Last In, First Out"],
    ["LLC", "Limited Liability Company"],
    ["LOI", "Letter Of Intent"],
    ["MMKT", "Money Market"],
    ["MTD", "Month to Date"],
    ["NAV", "Net Asset Value"],
    ["NCND", "Non Circumvent and Non Disclosure"],
    ["NDA", "Non Disclosure Agreement"],
    ["NI", "Net Income"],
    ["NYSE", "New York Stock Exchange"],
    ["OC", "Opportunity Cost"],
    ["OE", "Equity"],
    ["OE", "Owner’s Equity"],
    ["PC", "Percent"],
    ["PSP", "Profit Sharing Plan"],
    ["PV", "Present Value"],
    ["QTD", "Quarter to Date"],
    ["RE", "In Reference to"],
    ["RE", "Retained Earnings"],
    ["REIT", "Real Estate Investment Trust"],
    ["ROA", "Return On Assets"],
    ["ROCE", "Return On Capital Employed"],
    ["ROE", "Return On Equity"],
    ["ROI", "Return on Investment"],
    ["ROIC", "Return on Invested Capital"],
    ["RONA", "Return On Net Assets"],
    ["ROS", "Return on Sales"],
    ["SEC", "Securities Exchange Commission"],
    ["SIV", "Structured Investment Vehicle"],
    ["TSA", "Tax Sheltered Annuity"],
    ["TSR", "Total Shareholder Return"],
    ["WC", "Working Capital"],
    ["YTD", "Year to Date"],
    ["YTM", "Yield To Maturity"],
    ["AIDA", "Attention, Interest, Desire, Action"],
    ["AJAX", "Asynchronous JavaScript And XML"],
    ["API", "Application Program Interface"],
    ["ASP", "Application Service Provider"],
    ["CLV", "Customer Lifetime Value"],
    ["CMS", "Content Management System"],
    ["CPA", "Cost Per Action"],
    ["CPA", "Cost Per Acquisition"],
    ["CPC", "Cost Per Click"],
    ["CPL", "Cost Per Lead"],
    ["CPM", "Cost Per Thousand"],
    ["CPV", "Cost Per View"],
    ["CR", "Conversion Rate"],
    ["CRM", "Customer Relationship Management"],
    ["CRO", "Conversion Rate Optimisation"],
    ["CSS", "Cascading Style Sheets"],
    ["CTA", "Call To Action"],
    ["CTR", "Click Through Rate"],
    ["CX", "Customer Experience"],
    ["DM", "Direct Mail"],
    ["DM", "Direct Message"],
    ["DMP", "Data Management Platform"],
    ["DNS", "Domain Name System"],
    ["ECPM", "Effective CPM"],
    ["EPC", "Earnings Per Click"],
    ["EPM", "Earnings Per Thousand"],
    ["ESP", "Email Service Provider"],
    ["FB", "Facebook"],
    ["FTP", "File Transfer Protocol"],
    ["GA", "Google Analytics"],
    ["IM", "Instant Messaging"],
    ["IMAP", "Internet Message Access Protocol"],
    ["IP", "Intellectual property"],
    ["IPTV", "Internet Protocol Television"],
    ["ISP", "Internet Service Provider"],
    ["KPI", "Key Performance Indicator"],
    ["LTV", "Lifetime Value"],
    ["MLM", "Multilevel Marketing"],
    ["MVT", "Multivariate Testing"],
    ["OEM", "Original Equipment Manufacturer"],
    ["OS", "Operating System"],
    ["OS", "Open Source"],
    ["PPC", "Pay Per Click"],
    ["PPL", "Pay Per Lead"],
    ["PPV", "Pay Per View"],
    ["PR", "Page Rank"],
    ["PV", "Page Views"],
    ["QS", "Quality Score"],
    ["RFI", "Request For Information"],
    ["RON", "Run of Network"],
    ["RT", "Retweet"],
    ["RTB", "Real Time Bidding"],
    ["RTD", "Real Time Data"],
    ["SEM", "Search Engine Marketing"],
    ["SEO", "Search Engine Optimisation"],
    ["SERP", "Search Engine Results Page"],
    ["SM", "Social Media"],
    ["SME", "Small Medium Enterprise"],
    ["SMM", "Social Media Marketing"],
    ["SMO", "Social Media Optimisation"],
    ["SMP", "Social Media Platform"],
    ["SMS", "Short Message Service"],
    ["SOV", "Share Of Voice"],
    ["TLD", "Top Level Domain"],
    ["TOS", "Terms Of Service"],
    ["UI", "User Interface"],
    ["UGC", "User Generated Content"],
    ["UV", "Unique Visitor"],
    ["UX", "User Experience"],
    ["VOD", "Video On Demand"],
    ["VM", "Viral Marketing"],
    ["WOMM", "Word Of Mouth Marketing"],
    ["FYI", "For Your Information"],
    ["GMTA", "Great Minds Think Alike"],
    ["RUOK", "Are you Okay"],
    ["ASAP", "As Soon As Possible"],
    ["BTW", "By The Way"],
    ["EOD", "End Of Day"],
    ["ATTN", "Attention"],
    ["COB", "Close Of Business"],
    ["TBD", "To Be Decided"],
    ["RSVP", "Please Respond"],
    ["2MI", "Too Much Information"],
    ["2M2H", "Too Much To Handle"],
    ["AFC", "Away From Computer"],
    ["AEAP", "As Early As Possible"],
    ["AFK", "Away From Keyboard"],
    ["AMBW", "All My Best Wishes"],
    ["APP", "Application"],
    ["ATEOTD", "At The End Of The Day"],
    ["AWOL", "Away Without Leaving"],
    ["AWOL", "Absent Without Leave"],
    ["AYDY", "Are You Done Yet"],
    ["AYEC", "At Your Earliest Convenience"],
    ["AYW", "As You Want"],
    ["AYW", "As You Wish"],
    ["CHK", "Check"],
    ["HAG1", "Have A Good One"],
    ["HAU", "How About You"],
    ["H2CUS", "Hope To See You Soon"],
    ["HAND", "Have A Nice Day"],
    ["HF", "Have Fun"],
    ["IAC", "In Any Case"],
    ["IHNI", "I Have No Idea"],
    ["IMHO", "In My Humble Opinion"],
    ["IMO", "In My Opinion"],
    ["JLMK", "Just Let Me Know"],
    ["JW", "Just Wondering"],
    ["KUTGW", "Keep Up The Good Work"],
    ["OOTO", "Out Of The Office"],
    ["PLMK", "Please Let Me Know"],
    ["WYSIWYG", "What You See Is What You Get"],
    ["YOY", "Year Over Year"],
    ["YTD", "Year To Date"],
    ["AGT", "Agent"],
    ["HR", "Human Resources"],
    ["PR", "Public Relations"],
    ["QC", "Quality Control"],
    ["HQ", "Headquarters"],
    ["IPO", "Initial Public Offering"],
    ["LBO", "Limited Buy Out"],
    ["LLC", "Limited Liability Corporation"],
    ["API", "Application Program Interface"],
    ["CPU", "Central Processing Unit"],
    ["CSS", "Cascading Style Sheet"],
    ["FTP", "File Transport Protocol"],
    ["HTML", "Hyper Text Markup Language"],
    ["HTTP", "Hyper Text Transfer Protocol"],
    ["HTTPS", "Hyper Text Transfer Protocol Secure"],
    ["IM", "Instant Messaging"],
    ["IP", "Internet Protocol"],
    ["ISP", "Internet Service Provider"],
    ["OS", "Operating System"],
    ["QA", "Quality Assurance"],
    ["UI", "User Interface"],
    ["WYSIWYG", "What You See Is What You Get"],
    ["GTD", "Getting Things Done"],
    ["OHIO", "Only Handle It Once"],
    ["GPP", "Gross Primary Productivity"],
    ["HPCS", "High Productivity Computing Systems"],
    ["SDP", "Software Design and Productivity"],
    ["PI", "Productivity Index"],
    ["PLB", "Productivity Linked Bonus"],
    ["PC", "Productivity Commission"],
    ["SPR", "Software Productivity Research"],
    ["AA", "Attendance Allowance"],
    ["ADA", "Average Daily Attendance"],
    ["AMS", "Attendance Management System"],
    ["ATAAPS", "Automated Time, Attendance, and Production System"],
    ["COA", "Cost of Attendance"],
    ["FR", "Face Recognition"],
    ["RTT", "Real Time Tracking"],
    ["TRUE", "Tracking Real Time User Experience"],
    ["CTT", "Critical Time Tracking"],
    ["TTS", "Time Tracking Software"],
    ["TTS", "Time Tracking System"],
    ["RTTS", "Real Time Tracking System"],
    ["SU", "Start Up"],
    ["SUP", "Start Up Program"],
    ["SUE", "Start Up and Expansion"],
    ["IP", "Internet Protocol"],
    ["IETF", "Internet Engineering Task Force"],
    ["ATM", "Asynchronous Transfer Mode"],
    ["IT", "Information Technology"],
    ["ASCII", "American Standard Code for Information Interchange"],
    ["LAN", "Local Area Network"],
    ["SNMP", "Simple Network Management Protocol"],
    ["FTP", "File Transfer Protocol"],
    ["WWW", "World Wide Web"],
    ["DNS", "Domain Name System"],
    ["PDF", "Portable Document Format"],
    ["RF", "Radio Frequency"],
    ["XML", "Extensible Markup Language"],
    ["IANA", "Internet Assigned Numbers Authority"],
    ["SIP", "Session Initiation Protocol"],
    ["ITU", "International Telecommunication Union"],
    ["OSI", "Open Systems Interconnection"],
    ["PSTN", "Public Switched Telephone Network"],
    ["GUI", "Graphical User Interface"],
    ["EDI", "Electronic Data Interchange"],
    ["ISP", "Internet Service Provider"],
    ["TCP", "Transmission Control Protocol"],
    ["FDDI", "Fiber Distributed Data Interface"],
    ["ISO", "International Standards Organization"],
    ["UDP", "User Datagram Protocol"],
    ["ICAO", "International Civil Aviation Organization"],
    ["MAC", "Media Access Control"],
    ["MTP", "Message Transfer Part"],
    ["OS", "Operating System"],
    ["BGP", "Border Gateway Protocol"],
    ["OSPF", "Open Shortest Path First"],
    ["QA", "Quality Assurance"],
    ["SNA", "Systems Network Architecture"],
    ["VPN", "Virtual Private Network"],
    ["AIN", "Advanced Intelligent Network"],
    ["API", "Application Programming Interface"],
    ["ERP", "Enterprise Resource Planning"],
    ["NTIS", "National Technical Information Service"],
    ["RAM", "Random Access Memory"],
    ["AI", "Artificial Intelligence"],
    ["ARP", "Address Resolution Protocol"],
    ["BRI", "Basic Rate Interface"],
    ["CM", "Configuration Management"],
    ["CO", "Central Office"],
    ["DSL", "Digital Subscriber Line"],
    ["PDU", "Protocol Data Unit"],
    ["URL", "Uniform Resource Locator"],
    ["ANI", "Automatic Number Identification"],
    ["DES", "Data Encryption Standard"],
    ["DHCP", "Dynamic Host Configuration Protocol"],
    ["ITU", "International Telecommunication Union"],
    ["SMS", "Short Message Service"],
    ["WAP", "Wireless Application Protocol"],
    ["AES", "Advanced Encryption Standard"],
    ["ADP", "Automated Data Processing"],
    ["BAT", "Business Action Theory"],
    ["BCC", "Blind Copied"],
    ["BIMS", "Business Information Management Suite"],
    ["BPC", "Business Planning Cycle"],
    ["ETA", "Estimated Time of Arrival"],
    ["EXP", "Export"],
    ["GDP", "Gross Domestic Product"],
    ["GMP", "Good Manufacturing Practices"],
    ["TBD", "To Be Determined"],
    ["BID", "Break it down"],
    ["COB", "Close of business"],
    ["EOD", "End of day"],
    ["EOM", "End of message"],
    ["EOT", "End of thread"],
    ["EOW", "End of week"],
    ["ETA", "Estimated time of arrival"],
    ["FTE", "Full time employee"],
    ["FWIW", "For what it’s worth"],
    ["IAM", "In a meeting"],
    ["IMO", "In my opinion"],
    ["KISS", "Keep it simple stupid"],
    ["LET", "Leaving early today"],
    ["LMK", "Let me know"],
    ["MTD", "Month to date"],
    ["NIM", "No internal message"],
    ["OOO", "Out of office"],
    ["OT", "Off topic"],
    ["OTP", "On the phone"],
    ["PA", "Performance appraisal"],
    ["POC", "Point of contact"],
    ["PTE", "Part time employee"],
    ["PTO", "Paid time off"],
    ["NRN", "No reply necessary"],
    ["NSFW", "Not safe for work"],
    ["NWR", "Not work related"],
    ["RFD", "Request for discussion"],
    ["SME", "Subject matter expert"],
    ["TED", "Tell me, explain to me, describe to me"],
    ["TLDR", "Too long, didn’t read"],
    ["TLTR", "Too long to read"],
    ["TOS", "Terms of service"],
    ["TYT", "Take your time"],
    ["WFH", "Work from home"],
    ["WIIFM", "What’s in it for me"],
    ["WOM", "Word of mouth"],
    ["YTD", "Year to date"],
    ["ACCT", "Account"],
    ["AP", "Accounts payable"],
    ["AR", "Accounts receivable"],
    ["BS", "Balance sheet"],
    ["CPU", "Cost per unit"],
    ["CR", "Credit"],
    ["DR", "Debit"],
    ["EPS", "Earnings per share"],
    ["FIFO", "First in, first out"],
    ["IPO", "Initial public offering"],
    ["LIFO", "Last in, first out"],
    ["LWOP", "Leave without pay"],
    ["NAV", "Net assets value"],
    ["ROA", "Return on assets"],
    ["ROE", "Return on equity"],
    ["ROI", "Return on investment"],
    ["API", "Application program interface"],
    ["CPU", "Central processing unit"],
    ["CSS", "Cascading style sheet"],
    ["FTP", "File transport protocol"],
    ["HTML", "HyperText markup language"],
    ["HTTP", "HyperText transfer protocol"],
    ["HTTPS", "HyperText transfer protocol secure"],
    ["IM", "Instant messaging"],
    ["IP", "Internet protocol"],
    ["ISP", "Internet service provider"],
    ["OS", "Operating system"],
    ["QA", "Quality assurance"],
    ["UI", "User interface"],
    ["URL", "Universal resource locator"],
    ["UX", "User experience"],
    ["VPN", "Virtual private network"],
    ["RAM", "Random access memory"],
    ["ROR", "Ruby on Rails"],
    ["RSS", "Rich site summary"],
    ["RSS", "really simple syndication"],
    ["WYSIWYG", "What you see is what you get"],
    ["AIDA", "Attention, interest, desire, action"],
    ["B2B", "Business to business"],
    ["B2C", "Business to consumer"],
    ["BR", "Bounce rate"],
    ["CMS", "Content management system"],
    ["CPC", "Cost per click"],
    ["CTA", "Call to action"],
    ["CTR", "Click through rate"],
    ["CR", "Conversion rate"],
    ["CRM", "Customer relationship management"],
    ["DM", "Direct message"],
    ["DM", "direct mail"],
    ["ESP", "Email service provider"],
    ["GA", "Google Analytics"],
    ["KPI", "Key performance indicator"],
    ["PPC", "Pay per click"],
    ["PV", "Page view"],
    ["RFP", "Request for proposal"],
    ["ROS", "Run of site"],
    ["RT", "Retweet"],
    ["SEO", "Search engine optimization"],
    ["SM", "Social media"],
    ["SMB", "Small to medium business"],
    ["SWOT", "Strengths, weaknesses, opportunities, threats"],
    ["UV", "Unique visitor"],
    ["BD", "Business development"],
    ["CAO", "Chief analytics officer"],
    ["CDO", "Chief data officer"],
    ["CEO", "Chief executive officer"],
    ["CFO", "Chief financial officer"],
    ["CIO", "Chief information officer"],
    ["CMO", "Chief marketing officer"],
    ["COO", "Chief operating officer"],
    ["CPA", "Certified public accountant"],
    ["CSO", "Chief security officer"],
    ["CSR", "Corporate social responsibility"],
    ["CTO", "Chief technology officer"],
    ["CFP", "Certified financial planner"],
    ["DOE", "Depending on experience"],
    ["GC", "General counsel"],
    ["HR", "Human resources"],
    ["PM", "Project manager"],
    ["PR", "Public relations"],
    ["AC", "Air Conditioning"],
    ["AD", "Anno Domini"],
    ["AD", "In the Year of Our Lord"],
    ["AKA", "Also Known As"],
    ["AM", "Ante Meridiem"],
    ["AM", "before noon"],
    ["AM", "Amplitude Modification"],
    ["AM", "radio"],
    ["ASAP", "As Soon As Possible"],
    ["ATM", "Automated Teller Machine"],
    ["BC", "Before Christ"],
    ["BC", "Because"],
    ["BCE", "Before the Common Era"],
    ["BLT", "Bacon, Lettuce, Tomato"],
    ["BTW", "By The Way"],
    ["CC", "Credit Card"],
    ["CIA", "Central Intelligence Agency"],
    ["CO", "Commanding Officer"],
    ["CST", "Central Standard Time"],
    ["DOA", "Dead on Arrival"],
    ["DOT", "Department of Transportation"],
    ["DST", "Daylight Saving Time"],
    ["EST", "Eastern Standard Time"],
    ["ET", "Extra Terrestrial"],
    ["FAQ", "Frequently Asked Questions"],
    ["FBI", "Federal Bureau of Investigation"],
    ["FDR", "Franklin Delano Roosevelt"],
    ["FM", "Frequency Modification"],
    ["FM", "radio"],
    ["FYI", "For Your Information"],
    ["GI", "Government Issue"],
    ["GMO", "Genetically Modified"],
    ["IM", "Instant Message"],
    ["IMO", "In My Opinion"],
    ["IMHO", "In My Humble Opinion"],
    ["HAZ MAT", "Hazardous Material"],
    ["HMO", "Health Maintenence Organization"],
    ["ID", "Identification"],
    ["IQ", "Intelligence Quotient"],
    ["ISBN", "International Standard Book Number"],
    ["JFK", "John Fitzgerald Kennedy"],
    ["JV", "Junior Varsity"],
    ["KO", "Knockout"],
    ["LCD", "Liquid Crystal Display"],
    ["LED", "Light Emitting Diode"],
    ["LOL", "Laughing Out Loud"],
    ["MC", "Master of Ceremonies"],
    ["MLK", "Martin Luther King, Jr,"],
    ["MO", "Modus Operandi"],
    ["MRE", "Meals Ready to Eat"],
    ["MS", "Manuscript"],
    ["MST", "Mountain Standard Time"],
    ["MTG", "Magic: The Gathering"],
    ["MTD", "Month To Date"],
    ["NIB", "New In the Box"],
    ["NAFTA", "North American Free Trade Agreement"],
    ["NASA", "National Aeronautical and Space Administration"],
    ["NATO", "North Atlantic Treaty Organization"],
    ["NBA", "National Basketball Association"],
    ["NIB", "New In the Box"],
    ["NIMBY", "Not In My Backyard"],
    ["OJ", "Orange Juice"],
    ["OPEC", "Organization of Petroleum Exporting Countries"],
    ["PBJ", "Peanut Butter and Jelly"],
    ["PC", "Politically Correct"],
    ["PI", "Private Investigator"],
    ["PIN", "Personal Identification Number"],
    ["PM", "Post Meridiem"],
    ["PM", "after noon"],
    ["POTUS", "President of the United States"],
    ["POW", "Prisoner of War"],
    ["PPS", "Post Postscript"],
    ["PS", "Postscript"],
    ["PR", "Public Relations"],
    ["PSI", "Pounds Per Square Inch"],
    ["PST", "Pacific Standard Time"],
    ["RAM", "Random Access Memory"],
    ["RGB", "Red, Green, Blue"],
    ["RIP", "Rest in Peace,Requiescat In Pace"],
    ["ROM", "Read Only Memory"],
    ["ROTC", "Reserve Officers Training Corps"],
    ["ROYGBIV", "Red, Orange, Yellow, Green, Blue, Indigo, Violet"],
    ["RPG", "Role Playing Game"],
    ["RSVP", "Répondez S'il Vous Plaît"],
    ["RSVP", "Please Respond"],
    ["RV", "Recreational Vehicle"],
    ["SNAFU", "Systems Normal, All Fouled Up"],
    ["SOP", "Standard Operating Procedure"],
    ["SOS", "Save Our Souls"],
    ["SPF", "Sun Protection Factor"],
    ["TBA", "To Be Announced"],
    ["TEOTWAWKI", "The End Of The World As We Know It"],
    ["TGIF", "Thank God It's Friday"],
    ["TLC", "Tender Loving Care"],
    ["TV", "Television"],
    ["UFO", "Unidentified Flying Object"],
    ["UN", "United Nations"],
    ["UNICEF", "United Nations Children's Fund"],
    ["UPC", "Universal Product Code"],
    ["VIP", "Very Important Person"],
    ["VP", "Vice President"],
    ["WASP", "White Anglo Saxon Protestant"],
    ["WHO", "World Health Organization"],
    ["WOM", "Word of Mouth"],
    ["WYSIWYG", "What You See Is What You Get"],
    ["YTD", "Year To Date"],
    ["ZIP", "Zone Improvement Plan"],
    ["NATO", "North Atlantic Treaty Organization"],
    ["AIDS", "Acquired Immune Deficiency Syndrome"],
    ["OPEC", "Organization of the Petroleum Exporting Countries"],
    ["SPA", "Society of Professional Accountants"],
    ["WASP", "White Anglo Saxon Protestant"],
    ["ASAP", "as soon as possible"],
    ["CV", "Computer Vision"],
    ["DL", "Deep Learning"],
    ["CNN", "Convolutional Neural Networks"],
    ["ML", "Machine Learning"],
    ["NLP", "Natural Language Processing"],
    ["OCR", "Optical Character Recognition"],
    ["AI", "Artificial Intelligence"],
    ["RNN", "Recurrent Neural Networks"],
    ["NLG", "Natural Language Generation"],
    ["POV", "Proof of Value"],
    ["RPA", "Robotic Process Automation"],
    ["RPA", "Enterprise"],
    ["IA", "Intelligent Automation"],
    ["NLC", "Natural Language Classification"],
    ["TMI", "Too much information"],
    ["WBU", "What about you"],
    ["WBW", "Way back Wednesday, Follows the same theme as FBF and TBT"],
    ["WFH", "Work from home"],
    ["YOLO", "You only live once"],
    ["TBH", "To be honest"],
    ["TBBH", "To be brutally honest"],
    ["TBT", "Throwback Thursday, Like FBF, this involves sharing old photos,posts,"],
    ["TFW", "That feeling when Used for sharing a relatable experience,"],
    ["TGIF", "Thank God it’s Friday"],
    ["TIL", "Today I learned"],
    ["TLDR", "Too long, didn’t read,"],
    ["MFW", "My face when"],
    ["MTFBWY", "May the Force be with you, A “Star Wars” reference commonly used to give encouragement,"],
    ["NBD", "No big deal"],
    ["NM", "Not much"],
    ["NSFW", "Not safe for work"],
    ["NVM", "Never mind"],
    ["OH", "Used as context for quotes"],
    ["OMW", "On my way"],
    ["OOTD", "Outfit of the day"],
    ["OP", "Original poster"],
    ["OTP", "One true pairing, Commonly used in fandoms, Refers to two people,fictional characters that you consider the perfect pair/couple,"],
    ["PPL", "People"],
    ["ROFL", "Rolling on the floor laughing"],
    ["ROFLMAO", "Rolling on the floor laughing my a** off"],
    ["SFW", "Safe for work"],
    ["SMH", "Shaking my head, Used to express shock,disappointment,"],
    ["JK", "Just kidding, Used for conveying a light hearted tone,"],
    ["LMAO", "Laughing my a** off"],
    ["LMK", "Let me know"],
    ["LMS", "Like my status, Used for inviting people to engage with a post,"],
    ["LOL", "Laughing out loud"],
    ["MCM", "Man crush Monday, Chipotle put its own twist to this abbreviation to fit the product:"],
    ["HMB", "Hit me back"],
    ["HMU", "Hit me up"],
    ["HTH", "Here to help,happy to help"],
    ["ICYMI", "In case you missed it, Typically used when sharing content that’s not too current,"],
    ["IDC", "I don’t care"],
    ["IDK", "I don’t know"],
    ["IKR", "I know, right"],
    ["ILY", "I love you"],
    ["IMHO", "In my humble opinion"],
    ["IMO", "In my opinion"],
    ["IRL", "In real life"],
    ["FTFY", "Fixed that for you"],
    ["FTW", "For the win"],
    ["FYI", "For your information"],
    ["GG", "Good game"],
    ["GTR", "Got to run"],
    ["HBD", "Happy birthday"],
    ["HIFW", "How I feel when"],
    ["BRB", "Be right back"],
    ["BTAIM", "Be that as it may"],
    ["BTS", "Behind the scenes, Use this social media acronym when you’re giving your followers a behind the scenes look at what your brand is doing,"],
    ["BTW", "By the way"],
    ["DAE", "Does anyone else"],
    ["DYK", "Did you know"],
    ["ELI5", "Explain like I’m five, Often used in forums like Reddit when people are looking for the simplest explanation to more complex topics,"],
    ["AFAIK", "As far as I know"],
    ["AMA", "Ask me anything, Often used by celebrities, influencers, industry experts and regular social media users as an open invite for questions,"],
    ["BYOB", "Bring your own beer, byo"],
    ["AL", "Alabama"],
    ["AK", "Alaska"],
    ["AZ", "Arizona"],
    ["AR", "Arkansas"],
    ["CA", "California"],
    ["CO", "Colorado"],
    ["CT", "Connecticut"],
    ["DE", "Delaware"],
    ["FL", "Florida"],
    ["GA", "Georgia"],
    ["HI", "Hawaii"],
    ["ID", "Idaho"],
    ["IL", "Illinois"],
    ["IN", "Indiana"],
    ["IA", "Iowa"],
    ["KS", "Kansas"],
    ["KY", "Kentucky"],
    ["LA", "Louisiana"],
    ["ME", "Maine"],
    ["MD", "Maryland"],
    ["MA", "Massachusetts"],
    ["MI", "Michigan"],
    ["MN", "Minnesota"],
    ["MS", "Mississippi"],
    ["MO", "Missouri"],
    ["MT", "Montana"],
    ["NE", "Nebraska"],
    ["NV", "Nevada"],
    ["NH", "New Hampshire"],
    ["NJ", "New Jersey"],
    ["NM", "New Mexico"],
    ["NY", "New York"],
    ["NC", "North Carolina"],
    ["ND", "North Dakota"],
    ["OH", "Ohio"],
    ["OK", "Oklahoma"],
    ["OR", "Oregon"],
    ["PA", "Pennsylvania"],
    ["RI", "Rhode Island"],
    ["SC", "South Carolina"],
    ["SD", "South Dakota"],
    ["TN", "Tennessee"],
    ["TX", "Texas"],
    ["UT", "Utah"],
    ["VT", "Vermont"],
    ["VA", "Virginia"],
    ["WA", "Washington"],
    ["WV", "West Virginia"],
    ["WI", "Wisconsin"],
    ["WY", "Wyoming"],
    ["FBF", "Flashback Friday, A theme in which people share old pictures,posts with their followers/"],
    ["FBO", "Facebook official, When you make a public announcement on Facebook about a live event such as a new relationship, a change of job, etc,"],
    ["FF", "Follow Friday, A trend that started out on Twitter and involves giving a shoutout to people that you think deserve more recognition and followers,"],
    ["FOMO", "Fear of missing out, This often spurs people’s desire to keep up with social media in general, and is,often tapped for marketing such as through limited deals, exclusive product reveals and other tactics,"],
    ["API", "Application programming interface, It refers to a set of rules that determine how pieces of software interact with each other,"],
    ["CX", "Customer experience"],
    ["ESP", "Email service provider, The software you use for sending emails,"],
    ["GA", "Google Analytics"],
    ["ISP", "Internet service provider, The company that powers your internet service,"],
    ["PV", "Page views, The number of visitors landing on a specific page,"],
    ["RSS", "Really simple syndication,rich site summary, A feed of all the published content from a source, typically a blog,"],
    ["ROI", "Return on investment, It’s a measure of how much you earned considering the amount of money you spent to get those earnings"],
    ["SMB", "Small and midsize/medium businesses"],
    ["SMP", "Social media platform"],
    ["SMM", "Social media marketing"],
    ["SMO", "Social media optimization"],
    ["SRP", "Social relationship platform, A centralized platform that lets you publish content on multiple social media networks and then monitor and analyze the results"],
    ["TOS", "Terms of service"],
    ["UGC", "User generated content, Refers to any form of content in any format created by the users of a social network,"],
    ["CPC", "Cost per click, This is the dollar amount you pay for every person who clicks on your ad,"],
    ["CPM", "Cost per thousand impressions,cost per mile, Used for measuring ad impressions instead of clicks,"],
    ["CR", "Conversion rate, A measurement of the number of people who took the desired action divided by the number of people who could have,"],
    ["CRO", "Conversion rate optimization, This refers to the measures you take to improve conversion rate,"],
    ["CTA", "Call to action, A statement that encourages the audience to take a certain action,"],
    ["CTR", "Click through rate, The percentage of people who took the action of clicking on a link when given the option,"],
    ["B2B", "Business to business, Refers to companies that cater to the needs of other businesses,"],
    ["B2C", "Business to consumer, Refers to companies that sell products,services directly to customers,"],
    ["CMGR", "Community manager, They are responsible for managing and nurturing a brand’s relationship with its community", "not to be confused with social media manager"],
    ["CMS", "Content management system, The tool you use for editing, scheduling and publishing any form of written material for the web,"],
    ["MT", "Modified tweet, This is when you alter the text of a tweet before resharing it, You would typically create a modified tweet to shorten the text and fit the character limit,remove the poster’s handle (in case they have a private account),"],
    ["PM", "Private message, It’s a more generic term for one on one communications that aren’t visible to the public and includes DMs as well,"],
    ["RT", "When you share someone’s Tweet to your own feed, you are Retweeting them, Companies, influencers and celebrities alike often ask their followers to “RT” a post if they agree with it, It’s a great way to gain more shares and visibility for your Tweets"],
    ["FB", "Facebook"],
    ["IG", "Instagram"],
    ["LI", "LinkedIn"],
    ["YT", "YouTube"],
    ["TW", "Twitter"],
    ["1H", "1st Half"],
    ["24/7", "24 hours a day, seven days a week"],
    ["80/20", "for many events, roughly 80% of the effects come from 20% of the causes"],
    ["ADR", "American Depositary Receipt"],
    ["AI", "Artificial Intelligence"],
    ["AM", "Account manager"],
    ["AOP", "Adjusted Operating Profit"],
    ["AOP", "Annual Operating Plan"],
    ["AP", "Accounts payable"],
    ["ARPU", "Average revenue per user"],
    ["ASP", "Average selling price"],
    ["ASAP", "As soon as possible"],
    ["BAU", "Business As Usual"],
    ["BEP", "Break Even Point"],
    ["BIC", "Bank Identifier Code"],
    ["BLS", "Balance Sheet"],
    ["BMC", "Business Model Canvas"],
    ["BOM", "Bill of Materials"],
    ["BPO", "Business Process Outsourcing"],
    ["BPR", "Brief Project Report"],
    ["BPV", "Bank Payment Voucher"],
    ["BRD", "Business Requirements Document"],
    ["BRU", "Business Recovery Unit"],
    ["BRV", "Bank Receipt Voucher"],
    ["BTW", "By the way"],
    ["B2B", "Business to business"],
    ["B2C", "Business to Consumer"],
    ["B2G", "Business to government"],
    ["BUSI", "Business"],
    ["CAGR", "Compound annual growth rate"],
    ["CAO", "Chief Administrative Officer,Chief Accounting Officer"],
    ["CAPEX", "Capital Expenditure"],
    ["CAPM", "Capital asset pricing model[1]"],
    ["CBOE", "Chicago Board Options Exchange"],
    ["CBOT", "Chicago Board of Trade"],
    ["CDO", "Collateralized debt obligation,Chief Data Officer"],
    ["CDM", "Change and Data Management"],
    ["CDS", "Credit default swap"],
    ["CEO", "Chief executive officer"],
    ["COA", "Chart of Account"],
    ["CFA", "Chartered Financial Analyst"],
    ["CFD", "Contract for difference"],
    ["CFC", "Consumption of fixed capital"],
    ["CFCT", "Cash Flow Cycle Time"],
    ["CFM", "Certified Financial Manager"],
    ["CFO", "Chief Financial Officer"],
    ["CFS", "Consolidated Financial Statement"],
    ["CIA", "Certified Internal Auditor"],
    ["CIF", "Cost Insurance With Freight"],
    ["CIMA", "Chartered Institute of Management Accountants"],
    ["CIO", "Chief Information Officer, Chief Innovation Officer,Chief Investment Officer"],
    ["CIP", "Carriage and Insurance Paid"],
    ["CISA", "Certified Information Systems Auditor"],
    ["CISO", "Chief Information Security Officer"],
    ["CLA", "Chief Legal Officer"],
    ["CMA", "Certified Management Accountant"],
    ["CMFB", "Committee on monetary, finance and balance of payments statistics"],
    ["CMO", "Chief Marketing Officer"],
    ["COB", "Close of Business"],
    ["COC", "Cost of Credit[2],Cost of Capital[3]"],
    ["COD", "Cost of Debt[4],Cash on Delivery"],
    ["COE", "Center of Excellence,Cost of Equity[5]"],
    ["COGS", "Cost of Goods Sold"],
    ["COO", "Chief Operating Officer"],
    ["CPA", "Certified Public Accountant"],
    ["CPI", "Consumer Price Index"],
    ["CPO", "Chief People Officer,Chief Procurement Officer"],
    ["CPQ", "Configure, Price, Quote"],
    ["CPU", "Central Processing Unit"],
    ["CSI", "Corporate Social Investment"],
    ["CSO", "Chief Security Officer"],
    ["CSR", "Corporate social responsibility"],
    ["CRM", "Customer Relationship Management"],
    ["CVP", "Cost Volume Profit"],
    ["CTA", "Call to action"],
    ["CTO", "Chief Technology Officer"],
    ["CX", "Customer Experience"],
    ["CXO", "chief officer"],
    ["C2B", "Consumer to business"],
    ["CKM", "Customer Knowledge Management"],
    ["CTC", "Cost to company"],
    ["CA", "Current Account"],
    ["DDA", "Depletion Depreciation Amortization"],
    ["DI", "Dispatch information"],
    ["DIFOT", "Delivery in full on time, a variant of On Time In Full"],
    ["DMA", "Direct market access"],
    ["DPO", "Days Payable Outstanding"],
    ["DR", "Depositary receipt"],
    ["DSO", "Days Sales Outstanding"],
    ["DSP", "Delivery service provider"],
    ["DTP", "Desktop Publishing"],
    ["DVP", "Delivery versus payment"],
    ["EAR", "Effective annual rate"],
    ["EAY", "Effective Annual Yield"],
    ["EBITA", "Earnings before interest and taxes and amortization"],
    ["EBITDA", "Earnings before Interest, Taxes, Depreciation, and Amortization"],
    ["ECB", "European Central Bank"],
    ["EDI", "Electronic Data Interchange"],
    ["EFSM", "European Financial Stabilisation Mechanism"],
    ["EFTPOS", "Electronic Funds Transfer at Point of Sale"],
    ["EPS", "Earnings per share"],
    ["EXP", "Export"],
    ["EOB", "End of business"],
    ["EOD", "End of day"],
    ["EOM", "End of Message"],
    ["ERP", "Enterprise Resource Planning"],
    ["ETA", "Estimated Time of Arrival"],
    ["ETD", "Estimated Time of Departure,Estimated Time of Delivery"],
    ["EMI", "Equated Monthly Installment"],
    ["EPC", "Export Promotion Council"],
    ["ECGC", "Export Credit Guarantee Corporation of India"],
    ["EXW", "Ex Works"],
    ["FAB", "Feature Advantage Benefits"],
    ["FDP", "Finance Department"],
    ["FOB", "Freight On Board"],
    ["FIFO", "First In, First Out"],
    ["FL", "Financial leverage"],
    ["FOMC", "Federal Open Market Committee"],
    ["FPO", "Follow on public offer"],
    ["FIX", "Financial Information Exchange"],
    ["FSA", "Financial Services Authority"],
    ["FTE", "Full Time Equivalent"],
    ["FV", "Future Value"],
    ["FX", "Foreign exchange market"],
    ["FY", "Fiscal year,Financial year"],
    ["FYA", "For Your Action"],
    ["FYI", "For Your Information"],
    ["FOC", "Free Of Cost"],
    ["GAAP", "Generally Accepted Accounting Principles"],
    ["GAAS", "Generally Accepted Audit Standards"],
    ["GDP", "Gross Domestic Product"],
    ["GDPR", "General Data Protection Regulation"],
    ["GDR", "Global depository receipt"],
    ["GFCF", "Gross fixed capital formation"],
    ["GL", "General Ledger"],
    ["GMV", "Gross Merchandise Volume"],
    ["GP", "Gross Profit"],
    ["GPO", "Group purchasing organization"],
    ["GRN", "Goods Receipt Note"],
    ["GRNI", "Goods Receipt Not Invoiced"],
    ["GSV", "Gross Sales Value"],
    ["GVC", "Global Value Chain"],
    ["GMROII", "Gross Margin Return on Inventory Investment"],
    ["HMRC", "Her Majesty's Revenue and Customs"],
    ["HP", "Hire purchase"],
    ["HQ", "Headquarters"],
    ["HR", "Human Resources"],
    ["HRD", "Human Resource Development"],
    ["HS Code", "Harmonized Commodity Description and Coding System"],
    ["IAS", "International Accounting Standards"],
    ["IBAN", "International Bank Account Number"],
    ["ICB", "Industry Classification Benchmark"],
    ["ICRM", "Innovative Customer Relationship Management"],
    ["IE", "Interest expense"],
    ["IFRS", "International Financial Reporting Standard"],
    ["ILCLP", "IdentLogic Systems Customer Loyalty Program"],
    ["IMF", "International Monetary Fund"],
    ["IMP", "Import"],
    ["IPO", "Initial Public Offering"],
    ["IPT", "Item Per Transaction"],
    ["IR", "Interest Rate", "typically referring to an IR derivative product"],
    ["IRS", "Internal Revenue Service"],
    ["IRR", "Internal Rate of Return"],
    ["ISIN", "International Securities Identification Number"],
    ["ISM", "Institute of Supply Management"],
    ["ITT", "Invitation to Tender"],
    ["IYR", "In Year Revenue"],
    ["JIT", "Just in time"],
    ["JIS", "Just in sequence"],
    ["JST", "Joint Supervisory Team"],
    ["K", "Is used as an abbreviation for 1,000 For example, $225K would be understood to mean $225,000, and $36K would be understood to mean $3,600 Multiple K's are not commonly used to represent larger numbers In other words, it would look odd to use $12KK to represent $1,200,000"],
    ["KIBOR", "Karachi Interbank Offered Rate"],
    ["KPI", "Key Performance Indicator, a type of performance measurement An organization may use KPIs to evaluate its success,,to evaluate the success of a particular activity in which it is engaged"],
    ["KYC", "Know Your Customer, refers to due diligence activities that financial institutions and other regulated companies must perform to ascertain relevant information"],
    ["LBO", "Leveraged Buyout"],
    ["LC", "Letter of credit"],
    ["LIBOR", "London Interbank Offered Rate"],
    ["LE", "Latest Estimate"],
    ["LIFFE", "London International Financial Futures and Options Exchange"],
    ["LIFO", "Last In, First Out"],
    ["LLC", "Limited Liability Company"],
    ["LME", "London Metal Exchange"],
    ["LTV", "Loan to Value"],
    ["MBS", "mortgage backed security"],
    ["MGMT", "Management"],
    ["MIC", "Market Identifier Code"],
    ["MILE", "Maximum impact, little effort [10]"],
    ["MOQ", "Minimum Order Quantity"],
    ["MOU", "Memorandum of understanding"],
    ["MPC", "marginal propensity to consume"],
    ["MRO", "Maintenance, Repair, and Operations"],
    ["MRP", "Maximum Retail Price"],
    ["MSOD", "Monthly Statement of Select Operational Data"],
    ["MSRP", "Manufacturer's Suggested Retail Price"],
    ["MTD", "Month to date"],
    ["MWC", "Managerial Working Capital"],
    ["MPR", "Monthly Progress Report"],
    ["NAV", "Net asset value"],
    ["NCBO", "No Change of Beneficial Ownership"],
    ["NCND", "Non Circumvent and Non Disclosure"],
    ["NDA", "Non Disclosure Agreement"],
    ["NII", "Net Interest Income"],
    ["NIM", "Net Interest Margin"],
    ["NOA", "Net Operating Assets"],
    ["NOI", "Net Operating Income"],
    ["NOPAT", "Net Operating Profit After Tax"],
    ["NPA", "Non Performing Asset"],
    ["NPL", "Non performing loan"],
    ["NPV", "Net Present Value"],
    ["NTE", "Not To Exceed"],
    ["NYMEX", "New York Mercantile Exchange"],
    ["NYSE", "New York Stock Exchange"],
    ["OC", "Opportunity Cost"],
    ["OCF", "Operating cash flow"],
    ["OECD", "Organisation for Economic Co operation and Development"],
    ["OEM", "Original Equipment Manufacturer"],
    ["OIBDA", "Operating Income Before Depreciation And Amortization"],
    ["OKR", "Objectives and key results"],
    ["OOF", "Out of Facility"],
    ["OOO", "Out of Office"],
    ["OPEX", "Operating Expenditure,Operational Expenditure"],
    ["OTIF", "On Time In Full"],
    ["OTC", "Over the counter"],
    ["P2B", "Platform to Business"],
    ["PA", "Purchasing agent,Personal Assistant"],
    ["PA", "Promotional Activity"],
    ["PAT", "Profit After Tax"],
    ["PBT", "Profit Before Tax"],
    ["PE", "Private Equity"],
    ["PEG", "Price to earnings,growth ratio"],
    ["PHEK", "Planherstellungskosten ,Product Planning cost"],
    ["PFI", "Private Finance Initiative"],
    ["PMAC", "Period Moving Average Cost"],
    ["PO", "Profit Objective,Purchase Order"],
    ["POS", "Point of sale"],
    ["PPP", "Public private partnership"],
    ["PPP", "Purchasing power parity"],
    ["PPT", "Powerpoint presentation"],
    ["PR", "Purchase Requisition"],
    ["PTD", "Project to Date"],
    ["PWIN", "Percent win,percentage,revenue"],
    ["Q1", "quarters,accounting, calendar year,fiscal year"],
    ["Q2", "quarters,accounting, calendar year,fiscal year"],
    ["Q3", "quarters,accounting, calendar year,fiscal year"],
    ["Q4", "quarters,accounting, calendar year,fiscal year"],
    ["QC", "Quality control,Quality costs"],
    ["QTD", "Quarter to date"],
    ["RAQSCI", "Regulatory, Assurance of Supply, Quality, Service, Cost, Innovation"],
    ["RBI", "Reserve Bank of India"],
    ["RBA", "Reserve Bank of Australia"],
    ["RE", "Retained Earnings"],
    ["RFI", "Request for information"],
    ["RFP", "Request for Proposal"],
    ["RFQ", "Request for Quotation"],
    ["RFX", "Request for Information, Proposal,Quotation"],
    ["ROA", "Return on assets"],
    ["ROC", "Registration Of Company"],
    ["ROCE", "Return on Capital Employed"],
    ["ROE", "Return on Equity"],
    ["ROI", "Return on Investment"],
    ["ROIC", "Return on Invested Capital"],
    ["RONA", "Return on net assets"],
    ["ROS", "Return on Sales"],
    ["RR", "Resource rent"],
    ["RSP", "Retail selling price"],
    ["RWA", "Risk weighted asset"],
    ["RC", "Retail Company"],
    ["SAAS", "Software as a Service"],
    ["SBU", "Strategic Business Unit"],
    ["SBLC", "Stand By Letter of Credit"],
    ["SCM", "Supply Chain Management"],
    ["SCBA", "Social Cost Benefit Analysis"],
    ["SEBI", "Securities and Exchange Board,India"],
    ["SEC", "Securities and Exchange Commission"],
    ["SEDOL", "Stock Exchange Daily Official List"],
    ["SIOP", "Sales Inventory and Operations Plan"],
    ["SIR", "Stores Issuance Requisition"],
    ["SIV", "Structured investment vehicle"],
    ["SKU", "Stock keeping unit"],
    ["SLA", "Service Level Agreement"],
    ["SME", "Small and Medium Enterprises"],
    ["SOHO", "Small Office/Home Office"],
    ["SOP", "Standard Operating Procedure"],
    ["SOW", "Statement of Work"],
    ["SOX", "Sarbanes Oxley"],
    ["SROI", "Social return on investment"],
    ["SUA", "Start Up Agreement"],
    ["TB", "Transaction Banking"],
    ["TBC", "To Be Completed"],
    ["TBD", "To Be Defined"],
    ["TCO", "Total Cost of Ownership"],
    ["TCV", "Total Contract Value"],
    ["TOTW", "Time Off for Time Worked"],
    ["TQM", "Total Quality Management"],
    ["TSR", "Total Shareholder Return"],
    ["TTM", "Trailing Twelve Months"],
    ["USP", "Unique Selling Proposition"],
    ["UPI", "Unified Payment Interface"],
    ["VAD", "Value Added Distributor"],
    ["VAR", "Value Added Reseller"],
    ["VAT", "Value Added Tax"],
    ["VC", "Venture Capital"],
    ["VP", "Vice President"],
    ["WACC", "Weighted average cost of capital"],
    ["WC", "Working capital"],
    ["WFH", "Work From Home"],
    ["WIGs", "Wildly Important Goals"],
    ["WLL", "With Limited Liability"],
    ["WTI", "West Texas Intermediate"],
    ["WVN", "Withdraw Voucher Note"],
    ["WHT", "Withholding Tax"],
    ["WTO", "World Trade Organization"],
    ["WTD", "Week To Date"],
    ["WW", "World Wide"],
    ["YTD", "Year to date"],
    ["YTG", "Year to go"],
    ["YOY", "Year over year"],
    ["YTC", "Yet To Confirm"],
    ["FYF", "Full Year Forecast"],
    ["ZBB", "Zero Based Budgeting"],
    ["ZOPA", "Zone of Possible Agreement"],
    ["US", "United States"],
    ["AF", "Afghanistan"],
    ["AL", "Albania"],
    ["DZ", "Algeria"],
    ["AS", "American Samoa"],
    ["AD", "Andorra"],
    ["AO", "Angola"],
    ["AI", "Anguilla"],
    ["AQ", "Antarctica"],
    ["AG", "Antigua and Barbuda"],
    ["AR", "Argentina"],
    ["AM", "Armenia"],
    ["AW", "Aruba"],
    ["AU", "Australia"],
    ["AT", "Austria"],
    ["AZ", "Azerbaijan"],
    ["BS", "Bahamas"],
    ["BH", "Bahrain"],
    ["BD", "Bangladesh"],
    ["BB", "Barbados"],
    ["BY", "Belarus"],
    ["BE", "Belgium"],
    ["BZ", "Belize"],
    ["BJ", "Benin"],
    ["BM", "Bermuda"],
    ["BT", "Bhutan"],
    ["BO", "Bolivia"],
    ["BA", "Bosnia and Herzegovina"],
    ["BW", "Botswana"],
    ["BV", "Bouvet Island"],
    ["BR", "Brazil"],
    ["IO", "Indian Ocean"],
    ["BN", "Brunei"],
    ["BG", "Bulgaria"],
    ["BF", "Burkina Faso"],
    ["BI", "Burundi"],
    ["KH", "Cambodia"],
    ["CM", "Cameroon"],
    ["CA", "Canada"],
    ["CV", "Cape Verde"],
    ["KY", "Cayman Islands"],
    ["CF", "Central African Republic"],
    ["TD", "Chad"],
    ["CL", "Chile"],
    ["CN", "China"],
    ["CX", "Christmas Island"],
    ["CC", "Cocos"],
    ["CO", "Colombia"],
    ["KM", "Comoros"],
    ["CH", "Confederatio Helvetica (Switzerland)"],
    ["CG", "Congo"],
    ["CK", "Cook Islands"],
    ["CR", "Costa Rica"],
    ["CI", "Cote d'Ivoire"],
    ["HR", "Croatia"],
    ["CU", "Cuba"],
    ["CY", "Cyprus"],
    ["CZ", "Czech Republic"],
    ["CD", "Congo"],
    ["DK", "Denmark"],
    ["DJ", "Djibouti"],
    ["DM", "Dominica"],
    ["DO", "Dominican Republic"],
    ["TP", "East Timor"],
    ["EC", "Ecuador"],
    ["EG", "Egypt"],
    ["SV", "El Salvador"],
    ["GQ", "Equatorial Guinea"],
    ["ER", "Eritrea"],
    ["EE", "Estonia"],
    ["ET", "Ethiopia"],
    ["FK", "Falkland Islands"],
    ["FO", "Faroe Islands"],
    ["FJ", "Fiji Islands"],
    ["FI", "Finland"],
    ["FR", "France"],
    ["GF", "French Guiana"],
    ["PF", "French Polynesia"],
    ["TF", "French Southern and Antarctic Lands"],
    ["GA", "Gabon"],
    ["GM", "Gambia"],
    ["GE", "Georgia"],
    ["DE", "Germany"],
    ["GH", "Ghana"],
    ["GI", "Gibraltar"],
    ["GR", "Greece"],
    ["GL", "Greenland"],
    ["GD", "Grenada"],
    ["GP", "Guadeloupe"],
    ["GU", "Guam"],
    ["GT", "Guatemala"],
    ["GN", "Guinea"],
    ["GW", "Guinea Bissau"],
    ["GY", "Guyana"],
    ["HT", "Haiti"],
    ["HM", "Heard Island and McDonald Islands"],
    ["HN", "Honduras"],
    ["HK", "Hong Kong SAR"],
    ["HU", "Hungary"],
    ["IS", "Iceland"],
    ["IN", "India"],
    ["ID", "Indonesia"],
    ["IR", "Iran"],
    ["IQ", "Iraq"],
    ["IE", "Ireland"],
    ["IL", "Israel"],
    ["IT", "Italy"],
    ["JM", "Jamaica"],
    ["JP", "Japan"],
    ["JO", "Jordan"],
    ["KZ", "Kazakhstan"],
    ["KE", "Kenya"],
    ["KI", "Kiribati"],
    ["KR", "Korea"],
    ["KW", "Kuwait"],
    ["KG", "Kyrgyzstan"],
    ["LA", "Los Angeles"],
    ["LV", "Latvia"],
    ["LB", "Lebanon"],
    ["LS", "Lesotho"],
    ["LR", "Liberia"],
    ["LY", "Libya"],
    ["LI", "Liechtenstein"],
    ["LT", "Lithuania"],
    ["LU", "Luxembourg"],
    ["MK", "Macedonia, Former Yugoslav Republic of"],
    ["MG", "Madagascar"],
    ["MW", "Malawi"],
    ["MY", "Malaysia"],
    ["MV", "Maldives"],
    ["ML", "Mali"],
    ["MT", "Malta"],
    ["MH", "Marshall Islands"],
    ["MQ", "Martinique"],
    ["MR", "Mauritania"],
    ["MU", "Mauritius"],
    ["YT", "Mayotte"],
    ["MX", "Mexico"],
    ["FM", "Micronesia"],
    ["MD", "Moldova"],
    ["MC", "Monaco"],
    ["MN", "Mongolia"],
    ["MS", "Montserrat"],
    ["MA", "Morocco"],
    ["MZ", "Mozambique"],
    ["MM", "Myanmar"],
    ["NA", "Namibia"],
    ["NR", "Nauru"],
    ["NP", "Nepal"],
    ["NL", "Netherlands"],
    ["AN", "Netherlands Antilles"],
    ["NC", "New Caledonia"],
    ["NZ", "New Zealand"],
    ["NI", "Nicaragua"],
    ["NE", "Niger"],
    ["NG", "Nigeria"],
    ["NU", "Niue"],
    ["NF", "Norfolk Island"],
    ["KP", "North Korea"],
    ["MP", "Northern Mariana Islands"],
    ["NO", "Norway"],
    ["OM", "Oman"],
    ["PK", "Pakistan"],
    ["PW", "Palau"],
    ["PA", "Panama"],
    ["PG", "Papua New Guinea"],
    ["PY", "Paraguay"],
    ["PE", "Peru"],
    ["PH", "Philippines"],
    ["PN", "Pitcairn Islands"],
    ["PL", "Poland"],
    ["PT", "Portugal"],
    ["PR", "Puerto Rico"],
    ["QA", "Qatar"],
    ["RE", "Reunion"],
    ["RO", "Romania"],
    ["RU", "Russia"],
    ["RW", "Rwanda"],
    ["WS", "Samoa"],
    ["SM", "San Marino"],
    ["ST", "Sao Tome"],
    ["SA", "Saudi Arabia"],
    ["SN", "Senegal"],
    ["YU", "Serbia and Montenegro"],
    ["SC", "Seychelles"],
    ["SL", "Sierra Leone"],
    ["SG", "Singapore"],
    ["SK", "Slovakia"],
    ["SI", "Slovenia"],
    ["SB", "Solomon Islands"],
    ["SO", "Somalia"],
    ["ZA", "South Africa"],
    ["GS", "South Georgia,South Sandwich Islands"],
    ["ES", "Spain"],
    ["LK", "Sri Lanka"],
    ["SH", "St Helena"],
    ["KN", "St Kitts and Nevis"],
    ["LC", "St Lucia"],
    ["PM", "St Pierre and Miquelon"],
    ["VC", "St Vincent and the Grenadines"],
    ["SD", "Sudan"],
    ["SR", "Suriname"],
    ["SJ", "Svalbard and Jan Mayen"],
    ["SZ", "Swaziland"],
    ["SE", "Sweden"],
    ["CH", "Switzerland"],
    ["SY", "Syria"],
    ["TW", "Taiwan"],
    ["TJ", "Tajikistan"],
    ["TZ", "Tanzania"],
    ["TH", "Thailand"],
    ["TG", "Togo"],
    ["TK", "Tokelau"],
    ["TO", "Tonga"],
    ["TT", "Trinidad and Tobago"],
    ["TN", "Tunisia"],
    ["TR", "Turkey"],
    ["TM", "Turkmenistan"],
    ["TC", "Turks and Caicos Islands"],
    ["TV", "Tuvalu"],
    ["UG", "Uganda"],
    ["UA", "Ukraine"],
    ["AE", "United Arab Emirates"],
    ["UK", "United Kingdom"],
    ["US", "United States of America"],
    ["UM", "United States Minor Outlying Islands"],
    ["UY", "Uruguay"],
    ["UZ", "Uzbekistan"],
    ["VU", "Vanuatu"],
    ["VA", "Vatican City"],
    ["VE", "Venezuela"],
    ["VN", "Viet Nam"],
    ["VG", "Virgin Islands"],
    ["VI", "Virgin Islands"],
    ["WF", "Wallis and Futuna"],
    ["YE", "Yemen"],
    ["ZM", "Zambia"],
    ["ZW", "Zimbabwe"],
    ["lit", "Used to describe something that’s “happening,”"],
    ["on fleek", "On point"],
    ["slay", "Like “crushing it,” you’re “slaying” something if you do it exceptionally well,"],
    ["thirsty", "eager,desperate"],
    ["throwing shade", "denouncing, disrespecting,sarcastic"],
    ["yaas", "A particularly enthusiastic form of “yes,” You could use as many A’s as you’d like,"],
    ["clickbait", "fake,scam, provocative,trap"],
    ["cray", "crazy"],
    ["crush it", "doing well, crushing it"],
    ["facepalm", "stupid"],
    ["fam", "family,group, team,"],
    ["NoSQL", "Not only Structured Query Language"],
    ["AaaS", "Analytics as a Service"],
    ["IoT", "Internet of Things"],
];
