#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# echo "HUSKY_GIT_PARAMS" $HUSKY_GIT_PARAMS $0 $1 $2 $3 $4 $5 $m
npm run build && bash ./_bin/commit-all.sh . "auto commit-all projects pre-commit monorepo"
